### ISSUE TITLE
Feature Request Really 

### ISSUE THREAD

**Issue by barryboden** [SMTP2Graph/SMTP2Graph#24]
On the SMTP server side, is there a way to enable logging?
Used wireshark in the end to see what application way trying to send to the server.
The app we were trying to point to the smtp server, doesn't in case email addresses in <> 
so was sending 
`MAIL From: me@mydomain.com`
instead of 
`MAIL From: <me@mydomain.com>`
We managed to force that by including them within the sender address in that system, however it didn't include them in the To fields either.
Seems Exchange on prem is happy for them to missing even though they are the SMTP spec.
Is there anyway to make it less strict/put them in if missing?

**Comment by RoelVB** [comment]
Hi Barry,

Currently there is no way to make it less strict. We use [`smtp-server`](https://github.com/nodemailer/smtp-server) for this. The validation happens here:
https://github.com/nodemailer/smtp-server/blob/faf495f6649b4fdec0bd908caf6b89511c282af4/lib/smtp-connection.js#L563-L567

Since the spec says it should be surrounded by < >, I don't see why we would change that.

**Comment by barryboden** [comment]
Hi

I appreciate that you are following the rfc and that's understandable.    Seems both Exchange and postfix are less fussy, so I might be able to run an intermediary postfix install to relay from my app that doesn't follow the spec to this service.
